[versions]
precompose = "1.6.2"
maleficnav = "1.3.3"
maleficextensions = "1.4.4"
maleficcomps = "2.1.1"
malefictheme = "2.3.0"
kotlinter = "5.3.0"
compose = "1.9.3"
kotlin = "2.3.0"
composeHotReload = "1.1.0-alpha03"

[libraries]
precompose = { group = "moe.tlaster", name = "precompose", version.ref = "precompose" }
malefic-nav = { group = "xyz.malefic.compose", name = "nav", version.ref = "maleficnav" }
malefic-ext-core = { group = "xyz.malefic", name = "ext-core", version.ref = "maleficextensions" }
malefic-ext-compose = { group = "xyz.malefic", name = "ext-compose", version.ref = "maleficextensions" }
malefic-components = { group = "xyz.malefic.compose", name = "comps", version.ref = "maleficcomps" }
malefic-theming = { group = "xyz.malefic.compose", name = "theming", version.ref = "malefictheme" }

[plugins]
compose-kotlin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload"}

[bundles]
malefic-ext = ['malefic-ext-core', 'malefic-ext-compose']
malefic-compose = ['malefic-components', 'malefic-nav', 'malefic-theming']
